version: '3.4'

services:
  neo4j:
    image: neo4j
    ports:
        - "127.0.0.1:7687:7687"

  app:
    image: gcr.io/compliance-188015/depth-dashboard-backend
    build:
      context: backend
      dockerfile: backend/Dockerfile
    environment:
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASS: ${NEO4J_PASS}
      NEO4J_URI: ${NEO4J_URI:-bolt://neo4j:7687}
